version: "3"
services:
    server:
        image: backend
        ports:
            - 9090:8080
        environment:
            - MYSQL_HOST=mysqldb
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_POR=3306
        networks:
            - springmysql-net
        depends_on:
            - mysqldb

    mysqldb:
        image: mysql
        networks:
            - springmysql-net
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
        ports:
            - 3307:3306
        volumes:
            - ./Mydb:/var/lib/mysql
networks:
    springmysql-net:
